### ISSUE TITLE
APE_T crashes due to misused parameter

### ISSUE THREAD

**Issue by amir-rosenfeld** [yangyangyang127/APE#13]
cal_criterion uses a different number of features for training-free and finetuning.
For finetuning it returns:
`_, indices = torch.topk(criterion, k=min(cfg['training_feat_num'],len(criterion)))`
However, APE_training calls `self.indices = cal_criterion(cfg, clip_weights, cache_keys)` where the argument `training_free` defaults to `True`, hence the wrong configuration is used, eventually causing a dimension mismatch
`new_cache_keys[:, self.indices] = new_cache_keys [:, self.indices] + res_keys
RuntimeError: The size of tensor a (800) must match the size of tensor b (900) at non-singleton dimension 1`

**Comment by caoziyang1997** [comment]
0%|                                                                                                                                        | 0/7 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    main()
  File "main.py", line 271, in main
    APE_T(cfg, cache_keys, cache_values, val_features, val_labels, test_features, test_labels, clip_weights, clip_model, train_loader_F)
  File "main.py", line 135, in APE_T
    print(f"new_cache_keys[:, self.indices].shape: {new_cache_keys[:, self.indices].shape}")
UnboundLocalError: local variable 'new_cache_keys' referenced before assignment
同样的问题，如何解决

**Comment by caoziyang1997** [comment]
File "main.py", line 272, in <module>
    main()
  File "main.py", line 267, in main
    APE_T(cfg, cache_keys, cache_values, val_features, val_labels, test_features, test_labels, clip_weights, clip_model, train_loader_F)
  File "main.py", line 135, in APE_T
    new_cache_keys, new_clip_weights, R_FW = adapter(cache_keys, clip_weights, cache_values)
  File "/opt/conda/envs/APE/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/zhaojia/APE/utils.py", line 132, in forward
    new_cache_keys[:, self.indices] = new_cache_keys[:, self.indices] + res_keys
RuntimeError: The size of tensor a (800) must match the size of tensor b (900) at non-singleton dimension 1
如何解决

**Comment by kangang-jpg** [comment]
> 文件 “main.py”，第 272 行，在 main（） 文件中 文件“main.py”，第 267 行，在主 APE_T（cfg， cache_keys， cache_values， val_features， val_labels， test_features， test_labels， clip_weights， clip_model， train_loader_F） 文件“main.py”，第 135 行，APE_T new_cache_keys，new_clip_weights，R_FW = 适配器（cache_keys、clip_weights、cache_values）文件 “/opt/conda/envs/APE/lib/python3.7/site-packages/torch/nn/modules/module.py”，第 1194 行，_call_impl返回 forward_call（*input， **kwargs）文件“/root/zhaojia/APE/utils.py”，第 132 行，正向new_cache_keys[：， self.indices] = new_cache_keys[：， self.indices] + res_keys RuntimeError： 张量 a 的大小 （800） 必须与非单例维度 1 的张量 b 的大小 （900） 匹配 如何解决
你好，你的这个问题解决了嘛，我也遇到了，怎么回事呢
